version: '2'
services:
  pegster_apple-theme-mysql:
    container_name: pegster_apple-theme-mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=development
  pegster_apple-theme-wordpress:
    container_name: pegster_apple-theme-wordpress
    build: ./docker/wordpress
    ports:
      - 8080:80
    links:
      - pegster_apple-theme-mysql:mysql
    volumes:
      - .:/var/www/html/wp-content/themes/pegster_apple-theme/
